import { Task, Goal, Habit } from "./storage";

const today = new Date();
const tomorrow = new Date(today);
tomorrow.setDate(tomorrow.getDate() + 1);
const nextWeek = new Date(today);
nextWeek.setDate(nextWeek.getDate() + 7);
const nextMonth = new Date(today);
nextMonth.setDate(nextMonth.getDate() + 30);

export const SAMPLE_TASKS: Task[] = [
  {
    id: "task-1",
    title: "Complete project proposal",
    description: "Finish the Q2 project proposal and submit to manager",
    dueDate: today.toISOString(),
    dueTime: "14:00",
    priority: "high",
    category: "Work",
    completed: false,
    goalId: "goal-1",
    repeat: "none",
    createdAt: new Date(today.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "task-2",
    title: "Review team feedback",
    description: "Review and respond to team feedback from last meeting",
    dueDate: today.toISOString(),
    dueTime: "10:00",
    priority: "medium",
    category: "Work",
    completed: true,
    goalId: undefined,
    repeat: "none",
    createdAt: new Date(today.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    completedAt: new Date().toISOString(),
  },
  {
    id: "task-3",
    title: "Gym session",
    description: "1 hour workout - cardio and strength training",
    dueDate: today.toISOString(),
    dueTime: "17:00",
    priority: "high",
    category: "Health",
    completed: false,
    goalId: "goal-2",
    repeat: "daily",
    createdAt: new Date(today.getTime() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "task-4",
    title: "Buy groceries",
    description: "Milk, eggs, vegetables, chicken, rice",
    dueDate: tomorrow.toISOString(),
    dueTime: "18:00",
    priority: "medium",
    category: "Personal",
    completed: false,
    goalId: undefined,
    repeat: "none",
    createdAt: new Date(today.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "task-5",
    title: "Call dentist",
    description: "Schedule appointment for dental checkup",
    dueDate: tomorrow.toISOString(),
    dueTime: "09:00",
    priority: "low",
    category: "Health",
    completed: false,
    goalId: undefined,
    repeat: "none",
    createdAt: new Date(today.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "task-6",
    title: "Read technical article",
    description: "Read about React Native performance optimization",
    dueDate: nextWeek.toISOString(),
    dueTime: "19:00",
    priority: "low",
    category: "Learning",
    completed: false,
    goalId: "goal-3",
    repeat: "none",
    createdAt: new Date(today.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "task-7",
    title: "Prepare presentation",
    description: "Create slides for team meeting presentation",
    dueDate: nextWeek.toISOString(),
    dueTime: "15:00",
    priority: "high",
    category: "Work",
    completed: false,
    goalId: "goal-1",
    repeat: "none",
    createdAt: new Date(today.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "task-8",
    title: "Client meeting",
    description: "Quarterly review meeting with main client",
    dueDate: nextMonth.toISOString(),
    dueTime: "11:00",
    priority: "high",
    category: "Work",
    completed: false,
    goalId: undefined,
    repeat: "none",
    createdAt: new Date(today.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "task-9",
    title: "Update documentation",
    description: "Update API documentation with new endpoints",
    dueDate: nextWeek.toISOString(),
    dueTime: "16:00",
    priority: "medium",
    category: "Work",
    completed: false,
    goalId: undefined,
    repeat: "none",
    createdAt: new Date(today.getTime() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "task-10",
    title: "Plan weekend trip",
    description: "Research and book accommodation for weekend getaway",
    dueDate: nextMonth.toISOString(),
    dueTime: "10:00",
    priority: "low",
    category: "Personal",
    completed: false,
    goalId: undefined,
    repeat: "none",
    createdAt: new Date(today.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SAMPLE_GOALS: Goal[] = [
  {
    id: "goal-1",
    title: "Complete Q2 Project",
    description: "Successfully deliver the Q2 project on time and within budget",
    deadline: nextMonth.toISOString(),
    status: "active",
    progress: 65,
    category: "Work",
    milestones: [
      {
        id: "m1",
        goalId: "goal-1",
        title: "Requirements finalized",
        completed: true,
        completedAt: new Date(today.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "m2",
        goalId: "goal-1",
        title: "Design review",
        completed: true,
        completedAt: new Date(today.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "m3",
        goalId: "goal-1",
        title: "Development complete",
        completed: false,
      },
    ],
    createdAt: new Date(today.getTime() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "goal-2",
    title: "Get Fit",
    description: "Exercise 4 times per week and reach target weight",
    deadline: nextMonth.toISOString(),
    status: "active",
    progress: 45,
    category: "Health",
    milestones: [
      {
        id: "m4",
        goalId: "goal-2",
        title: "Join gym",
        completed: true,
        completedAt: new Date(today.getTime() - 20 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "m5",
        goalId: "goal-2",
        title: "Lose 5 lbs",
        completed: false,
      },
    ],
    createdAt: new Date(today.getTime() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "goal-3",
    title: "Learn React Native",
    description: "Complete React Native course and build 2 projects",
    deadline: nextMonth.toISOString(),
    status: "active",
    progress: 30,
    category: "Learning",
    milestones: [
      {
        id: "m6",
        goalId: "goal-3",
        title: "Course started",
        completed: true,
        completedAt: new Date(today.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ],
    createdAt: new Date(today.getTime() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "goal-4",
    title: "Read 12 Books",
    description: "Read one book per month throughout the year",
    deadline: nextMonth.toISOString(),
    status: "active",
    progress: 25,
    category: "Personal",
    milestones: [],
    createdAt: new Date(today.getTime() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "goal-5",
    title: "Save $5000",
    description: "Save money for emergency fund",
    deadline: nextMonth.toISOString(),
    status: "active",
    progress: 55,
    category: "Finance",
    milestones: [],
    createdAt: new Date(today.getTime() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SAMPLE_HABITS: Habit[] = [
  {
    id: "habit-1",
    title: "Morning Meditation",
    description: "10 minutes of meditation every morning",
    frequency: "daily",
    daysOfWeek: [],
    color: "#0a7ea4",
    category: "Wellness",
    completedDates: generateCompletedDates(25, 30),
    createdAt: new Date(today.getTime() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "habit-2",
    title: "Exercise",
    description: "30 minutes of physical activity",
    frequency: "daily",
    daysOfWeek: [],
    color: "#22C55E",
    category: "Health",
    completedDates: generateCompletedDates(28, 30),
    createdAt: new Date(today.getTime() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "habit-3",
    title: "Read",
    description: "Read for 30 minutes before bed",
    frequency: "daily",
    daysOfWeek: [],
    color: "#F59E0B",
    category: "Learning",
    completedDates: generateCompletedDates(15, 20),
    createdAt: new Date(today.getTime() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "habit-4",
    title: "Drink Water",
    description: "Drink 8 glasses of water daily",
    frequency: "daily",
    daysOfWeek: [],
    color: "#06B6D4",
    category: "Health",
    completedDates: generateCompletedDates(35, 60),
    createdAt: new Date(today.getTime() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "habit-5",
    title: "Code Review",
    description: "Review team's code and provide feedback",
    frequency: "weekly",
    daysOfWeek: [1, 3, 5], // Monday, Wednesday, Friday
    color: "#8B5CF6",
    category: "Work",
    completedDates: generateCompletedDates(10, 12),
    createdAt: new Date(today.getTime() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "habit-6",
    title: "Journal",
    description: "Write in journal for 15 minutes",
    frequency: "daily",
    daysOfWeek: [],
    color: "#EC4899",
    category: "Personal",
    completedDates: generateCompletedDates(20, 35),
    createdAt: new Date(today.getTime() - 35 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

function generateCompletedDates(completed: number, total: number): string[] {
  const dates: string[] = [];
  for (let i = total - 1; i >= 0; i--) {
    if (Math.random() < completed / total) {
      const date = new Date(today);
      date.setDate(date.getDate() - i);
      dates.push(date.toISOString().split("T")[0]);
    }
  }
  return dates;
}
